# Generated by Django 5.2.1 on 2025-07-01 02:47

import core.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('freq', core.fields.ChoiceIntegerField([(0, 'Yearly'), (1, 'Monthly'), (2, 'Weekly'), (3, 'Daily'), (4, 'Hourly'), (5, 'Minutely'), (6, 'Secondly')], 3, default=3)),
                ('interval', core.fields.LimitedDecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('by_week_day', core.fields.ChoicesStringArrayField(blank=True, choices=['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'], default=list)),
                ('by_month_day', core.fields.ChoicesNumberArrayField(blank=True, choices=range(1, 32), default=list)),
                ('by_month', core.fields.ChoicesNumberArrayField(blank=True, choices=range(1, 13), default=list)),
                ('by_year_day', core.fields.ChoicesNumberArrayField(blank=True, choices=range(1, 367), default=list)),
                ('by_week_no', core.fields.ChoicesNumberArrayField(blank=True, choices=range(1, 54), default=list)),
                ('by_hour', core.fields.ChoicesNumberArrayField(blank=True, choices=range(0, 24), default=list)),
                ('by_minute', core.fields.ChoicesNumberArrayField(blank=True, choices=range(0, 60), default=list)),
                ('by_second', core.fields.ChoicesNumberArrayField(blank=True, choices=range(0, 60), default=list)),
                ('by_set_position', core.fields.ChoicesNumberArrayField(blank=True, choices=range(-31, 32), default=list)),
                ('count', core.fields.OptionalLimitedDecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', core.fields.DefaultTodayField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', core.fields.OptionalDateField(blank=True, null=True)),
                ('start_time', core.fields.OptionalLimitedTimeField(blank=True, null=True)),
                ('end_time', core.fields.OptionalLimitedTimeField(blank=True, null=True)),
                ('week_start', core.fields.ChoiceIntegerField([(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], 0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('color', core.fields.ColorField(blank=True, default='', help_text='Hex color code, e.g. #FF5733', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('description', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('date_start', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('date_end', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('date_created', core.fields.AutoCreatedAtField(auto_now_add=True)),
                ('date_completed', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('is_archived', core.fields.DefaultBooleanField(False)),
                ('parent_goal', core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.goal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('description', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('date_start', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('date_end', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('date_created', core.fields.AutoCreatedAtField(auto_now_add=True)),
                ('date_completed', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('is_archived', core.fields.DefaultBooleanField(False)),
                ('threshold_percent', core.fields.LimitedDecimalField(decimal_places=2, default=80, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('goal', core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.goal')),
                ('schedule', core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', core.fields.DefaultNowField(blank=True, default=django.utils.timezone.now, null=True)),
                ('habit', core.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity.habit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('description', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('date_start', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('date_end', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('date_created', core.fields.AutoCreatedAtField(auto_now_add=True)),
                ('date_completed', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('is_archived', core.fields.DefaultBooleanField(False)),
                ('importance', core.fields.LimitedDecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('due_date', core.fields.OptionalDateField(blank=True, null=True)),
                ('goal', core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.goal')),
                ('habit', core.fields.OptionalSetNullOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productivity.habit')),
                ('schedule', core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.schedule')),
            ],
            options={
                'unique_together': {('due_date', 'importance')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('description', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('date_start', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('date_end', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('date_created', core.fields.AutoCreatedAtField(auto_now_add=True)),
                ('date_completed', core.fields.OptionalDateTimeField(blank=True, null=True)),
                ('is_archived', core.fields.DefaultBooleanField(False)),
                ('location', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('tags', core.fields.OptionalManyToManyField(blank=True, to='productivity.tag')),
                ('task', core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
