# Generated by Django 5.2.1 on 2025-07-09 10:27

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='excuse',
            field=core.fields.MediumCharField(blank=True, default='', max_length=255),
        ),
    ]
