# Generated by Django 5.2.1 on 2025-06-21 00:21

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='is_cancelled',
            new_name='is_archived',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_cancelled',
            new_name='is_archived',
        ),
        migrations.AddField(
            model_name='habit',
            name='date_completed',
            field=core.fields.OptionalDateField(blank=True, null=True),
        ),
    ]
