# Generated by Django 5.2.1 on 2025-06-21 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_rename_is_cancelled_goal_is_archived_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
