# Generated by Django 5.2.1 on 2025-07-15 21:41

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_event_excuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=core.fields.DefaultTodayField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
