# Generated by Django 5.2.1 on 2025-06-21 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_rename_created_at_event_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='date_start',
        ),
    ]
