# Generated by Django 5.2.1 on 2025-06-21 00:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0004_rename_end_event_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date_end',
            field=core.fields.OptionalDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='date_start',
            field=core.fields.OptionalDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='date_end',
            field=core.fields.OptionalDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='date_start',
            field=core.fields.OptionalDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=core.fields.OptionalDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=core.fields.OptionalDateTimeField(blank=True, null=True),
        ),
    ]
