# Generated by Django 5.2.1 on 2025-07-22 04:59

import core.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0004_redeempoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeempoint',
            name='log',
            field=core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.habitlog'),
        ),
    ]
