# Generated by Django 5.2.1 on 2025-06-21 00:38

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0005_alter_goal_date_end_alter_goal_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date_completed',
            field=core.fields.OptionalDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='date_completed',
            field=core.fields.OptionalDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=core.fields.OptionalDateTimeField(blank=True, null=True),
        ),
    ]
