# Generated by Django 5.2.1 on 2025-06-21 00:46

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0006_alter_goal_date_completed_alter_habit_date_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_completed',
            field=core.fields.OptionalDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=core.fields.DefaultBooleanField(False),
        ),
    ]
