# Generated by Django 5.2.1 on 2025-06-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0007_event_date_completed_event_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
