# Generated by Django 5.2.1 on 2025-08-02 02:01

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0007_event_created_at_event_updated_at_goal_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redeempoint',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redeempoint',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
