# Generated by Django 5.2.1 on 2025-06-21 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0008_remove_task_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='all_day',
        ),
    ]
