# Generated by Django 5.2.1 on 2025-08-02 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0008_alter_event_created_at_alter_event_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitlog',
            old_name='date_created',
            new_name='date_logged',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_created',
        ),
    ]
