# Generated by Django 5.2.1 on 2025-06-21 03:23

import core.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0009_remove_event_all_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='habit',
            field=core.fields.OptionalOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.habit'),
        ),
    ]
