# Generated by Django 5.2.1 on 2025-06-21 05:32

import core.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0010_alter_task_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitlog',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='habitlog',
            name='date',
        ),
        migrations.AddField(
            model_name='habitlog',
            name='event',
            field=core.fields.CascadeRequiredForeignKey(default=70, on_delete=django.db.models.deletion.CASCADE, to='productivity.event'),
            preserve_default=False,
        ),
    ]
