# Generated by Django 5.2.1 on 2025-06-21 05:34

import core.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0011_remove_habitlog_completed_at_remove_habitlog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='event',
            field=core.fields.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productivity.event'),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='habit',
            field=core.fields.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productivity.habit'),
        ),
    ]
