# Generated by Django 5.2.1 on 2025-06-21 05:44

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0012_alter_habitlog_event_alter_habitlog_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitlog',
            name='event',
        ),
        migrations.AddField(
            model_name='habitlog',
            name='date_created',
            field=core.fields.DefaultNowField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
