# Generated by Django 5.2.1 on 2025-06-21 06:02

import core.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0013_remove_habitlog_event_habitlog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='habit',
            field=core.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity.habit'),
        ),
    ]
