# Generated by Django 5.2.1 on 2025-06-23 07:52

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0014_alter_habitlog_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='freq',
            field=core.fields.ChoiceIntegerField([(0, 'Yearly'), (1, 'Monthly'), (2, 'Weekly'), (3, 'Daily'), (4, 'Hourly'), (5, 'Minutely'), (6, 'Secondly')], 3, default=3),
        ),
    ]
