# Generated by Django 5.2.1 on 2025-06-23 07:55

import core.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0015_alter_schedule_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='count',
            field=core.fields.LimitedDecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='interval',
            field=core.fields.LimitedDecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
