# Generated by Django 5.2.1 on 2025-06-25 05:29

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0016_alter_schedule_count_alter_schedule_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=core.fields.DefaultTodayField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
