# Generated by Django 5.2.1 on 2025-06-25 11:20

import core.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0018_alter_schedule_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='count',
            field=core.fields.LimitedDecimalField(decimal_places=2, default=300, max_digits=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
