# Generated by Django 5.2.1 on 2025-06-26 06:50

import core.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0019_alter_schedule_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='count',
            field=core.fields.OptionalLimitedDecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
