# Generated by Django 5.2.1 on 2025-06-26 11:45

import core.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0022_alter_schedule_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='schedule',
            field=core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.schedule'),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule',
            field=core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productivity.schedule'),
        ),
    ]
