# Generated by Django 5.2.1 on 2025-06-26 11:53

import core.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0023_alter_habit_schedule_alter_task_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='habit',
            field=core.fields.OptionalSetNullOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productivity.habit'),
        ),
    ]
