# Generated by Django 5.2.1 on 2025-06-20 02:26

import core.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyFat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_fat_percent', core.fields.DecimalField(decimal_places=3, max_digits=10)),
                ('date', core.fields.AutoCreatedAtField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('category', core.fields.ChoiceIntegerField([(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner'), (3, 'Snack')])),
                ('calories', core.fields.DecimalField(decimal_places=3, max_digits=10)),
                ('date', core.fields.DefaultNowField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaistMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist_cm', core.fields.DecimalField(decimal_places=3, max_digits=10)),
                ('date', core.fields.AutoCreatedAtField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeighIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', core.fields.DecimalField(decimal_places=3, max_digits=10)),
                ('date', core.fields.AutoCreatedAtField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('category', core.fields.ChoiceIntegerField([(0, 'Cardio'), (1, 'Upper Body'), (2, 'Lower Body'), (3, 'Core'), (4, 'Full Body'), (5, 'Other')])),
                ('duration_minutes', core.fields.DecimalField(decimal_places=3, max_digits=10)),
                ('calories_burned', core.fields.DecimalField(decimal_places=3, max_digits=10)),
                ('date', core.fields.DefaultNowField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
