# Generated by Django 5.2.1 on 2025-07-03 05:48

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyfat',
            name='date',
            field=core.fields.DefaultNowField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='waistmeasurement',
            name='date',
            field=core.fields.DefaultNowField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='weighin',
            name='date',
            field=core.fields.DefaultNowField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
