# Generated by Django 5.2.1 on 2025-08-02 02:01

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_bodyfat_created_at_bodyfat_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyfat',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bodyfat',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waistmeasurement',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waistmeasurement',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weighin',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weighin',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
