services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - db

    volumes:
      - ./server:/app

  frontend:
    build: ./web
    ports:
      - "3000:80"
    volumes:
      - ./web:/app
      

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
