# Generated by Django 5.2.1 on 2025-06-28 01:32

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', core.fields.ShortCharField(blank=True, default='', max_length=50, unique=True)),
                ('value', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('description', core.fields.MediumCharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
