# Generated by Django 5.2.1 on 2025-07-05 06:14

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=core.fields.LongCharField(blank=True, default='', max_length=1023),
        ),
    ]
