# Generated by Django 5.2.1 on 2025-08-02 02:01

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_setting_created_at_setting_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
