# Generated by Django 5.2.1 on 2025-07-02 01:22

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('body', core.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('file', core.fields.FileField(upload_to='notes/')),
                ('created_at', core.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', core.fields.AutoUpdatedAtField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
