# Generated by Django 5.2.1 on 2025-07-02 01:23

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=core.fields.FileField(upload_to='uploads/notes/'),
        ),
    ]
