# Generated by Django 5.2.1 on 2025-07-03 06:46

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=core.fields.OptionalManyToManyField(blank=True, to='issues.tag'),
        ),
    ]
