# Generated by Django 5.2.1 on 2025-08-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_ticket_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
    ]
