# Generated by Django 5.2.1 on 2025-08-21 08:31

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_alter_comment_created_at_alter_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', core.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', core.fields.AutoUpdatedAtField(auto_now=True)),
                ('title', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('description', core.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('file', core.fields.FileField(upload_to='releases/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
