# Generated by Django 5.2.1 on 2025-05-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=300)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
