# Generated by Django 5.2.1 on 2025-05-16 06:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_journal_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, unique=True)),
                ('nature', models.CharField(choices=[('1', 'Expense'), ('2', 'Income'), ('3', 'Transfer'), ('4', 'Payable'), ('5', 'Receivable')], default='3', max_length=20)),
                ('logo', models.CharField(default='star', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('datetime_transacted', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_category', to='myapp.category')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_receiver', to='myapp.account')),
                ('transmitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_transmitter', to='myapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(blank=True, default='', max_length=30)),
                ('lent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('datetime_opened', models.DateTimeField(auto_now_add=True)),
                ('datetime_due', models.DateTimeField(blank=True, null=True)),
                ('datetime_closed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment', models.ManyToManyField(blank=True, related_name='payment_receivable', to='myapp.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(blank=True, default='', max_length=30)),
                ('datetime_opened', models.DateTimeField(auto_now_add=True)),
                ('datetime_due', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('datetime_closed', models.DateTimeField(blank=True, null=True)),
                ('borrowed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('payment', models.ManyToManyField(blank=True, related_name='payment_payable', to='myapp.transaction')),
            ],
        ),
    ]
