# Generated by Django 5.2.1 on 2025-05-18 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='myapp.goal'),
        ),
    ]
