# Generated by Django 5.2.1 on 2025-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_goal_parent_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
