# Generated by Django 5.2.1 on 2025-06-20 02:26

import core.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('description', core.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('datetime_created', core.fields.DefaultNowField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', core.fields.ShortCharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', core.fields.OptionalEmailField(blank=True, max_length=254, null=True)),
                ('recovery_email', core.fields.OptionalEmailField(blank=True, max_length=254, null=True)),
                ('associated_email', core.fields.OptionalEmailField(blank=True, max_length=254, null=True)),
                ('authenticator_email', core.fields.OptionalEmailField(blank=True, max_length=254, null=True)),
                ('profile_url', core.fields.OptionalURLField(blank=True, null=True)),
                ('pin', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('login_method', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('recovery_phone', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('password', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('username', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('account_number', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('custom_authenticator', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('notes', core.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('backup_codes', core.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('date_created', core.fields.OptionalDateField(blank=True, null=True)),
                ('authenticator_app', core.fields.ChoiceIntegerField([(0, 'None'), (1, 'Google Authenticator'), (2, 'Authy'), (3, 'Microsoft Authenticator'), (4, '1Password'), (5, 'Other')])),
                ('added_at', core.fields.AutoCreatedAtField(auto_now_add=True)),
                ('billing_accounts', core.fields.OptionalManyToManyField(blank=True, to='finance.account')),
                ('platform', core.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.platform')),
            ],
        ),
    ]
