# Generated by Django 5.2.1 on 2025-07-14 10:32

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_dream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('description', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('document_type', core.fields.ChoiceIntegerField([(0, 'ID'), (1, 'Certificate'), (2, 'Contract'), (3, 'Bill'), (4, 'Other')], 4, default=4)),
                ('file', core.fields.FileField(upload_to='documents/')),
                ('issued_date', core.fields.OptionalDateField(blank=True, null=True)),
                ('expiry_date', core.fields.OptionalDateField(blank=True, null=True)),
                ('is_active', core.fields.DefaultBooleanField(True)),
                ('created_at', core.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', core.fields.AutoUpdatedAtField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
