# Generated by Django 5.2.1 on 2025-07-15 21:41

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='date_created',
            field=core.fields.DefaultTodayField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
