# Generated by Django 5.2.1 on 2025-08-02 02:01

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_credential_created_at_credential_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dream',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dream',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
