# Generated by Django 5.2.1 on 2025-08-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_alter_credential_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='added_at',
        ),
    ]
