# Generated by Django 5.2.1 on 2025-08-02 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_remove_credential_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='datetime_created',
        ),
    ]
