# Generated by Django 5.2.1 on 2025-07-14 10:32

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_remove_receivable_charged_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemToBring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', core.fields.DecimalField(decimal_places=3, max_digits=10)),
                ('cost', core.fields.AmountField(decimal_places=2, max_digits=10)),
                ('packed', core.fields.DefaultBooleanField(False)),
                ('inventory_item', core.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.personalitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('city', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('purpose', core.fields.ChoiceIntegerField([(0, 'Work'), (1, 'Study'), (2, 'Vacation'), (3, 'Relocation'), (4, 'Other')], 4, default=4)),
                ('target_date', core.fields.OptionalDateField(blank=True, null=True)),
                ('status', core.fields.ChoiceIntegerField([(0, 'Planning'), (1, 'Booking'), (2, 'Approved'), (3, 'On Hold'), (4, 'Completed')], 0)),
                ('notes', core.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('created_at', core.fields.AutoCreatedAtField(auto_now_add=True)),
                ('items_to_bring', core.fields.OptionalManyToManyField(blank=True, to='travel.itemtobring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('cost', core.fields.AmountField(decimal_places=2, max_digits=10)),
                ('completed', core.fields.DefaultBooleanField(False)),
                ('plan', core.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
