# Generated by Django 5.2.1 on 2025-07-14 10:46

import core.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_receivable_charged_to_and_more'),
        ('personal', '0003_document'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtobring',
            options={'verbose_name_plural': 'items to bring'},
        ),
        migrations.AddField(
            model_name='itemtobring',
            name='document',
            field=core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.document'),
        ),
        migrations.AlterField(
            model_name='itemtobring',
            name='inventory_item',
            field=core.fields.CascadeOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.personalitem'),
        ),
    ]
