# Generated by Django 5.2.1 on 2025-07-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_itemtobring_options_itemtobring_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtobring',
            name='cost',
        ),
    ]
