# Generated by Django 5.2.1 on 2025-08-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_itemtobring_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='created_at',
        ),
    ]
