# Generated by Django 5.2.1 on 2025-08-02 01:57

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_travelplan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtobring',
            name='created_at',
            field=core.fields.OptionalDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='itemtobring',
            name='updated_at',
            field=core.fields.OptionalDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='created_at',
            field=core.fields.OptionalDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='updated_at',
            field=core.fields.OptionalDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='created_at',
            field=core.fields.OptionalDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='updated_at',
            field=core.fields.OptionalDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
