# Generated by Django 5.2.1 on 2025-07-13 10:30

import core.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_receivable_charged_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivable',
            name='charged_to',
        ),
        migrations.AddField(
            model_name='receivable',
            name='charge_transaction',
            field=core.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction'),
        ),
    ]
