# Generated by Django 5.2.1 on 2025-08-02 02:01

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_account_created_at_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buylistitem',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buylistitem',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payable',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payable',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalitem',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalitem',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receivable',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receivable',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=core.fields.AutoCreatedAtField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=core.fields.AutoUpdatedAtField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
