# Generated by Django 5.2.1 on 2025-08-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_account_created_at_alter_account_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='datetime_added',
        ),
    ]
