# Generated by Django 5.2.1 on 2025-08-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_account_datetime_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buylistitem',
            name='added_at',
        ),
    ]
