# Generated by Django 5.2.1 on 2025-06-20 02:26

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('company', core.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('location', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('link', core.fields.OptionalURLField(blank=True, null=True)),
                ('salary', core.fields.MediumCharField(blank=True, default='', max_length=255)),
                ('deadline', core.fields.OptionalDateField(blank=True, null=True)),
                ('applied_date', core.fields.OptionalDateField(blank=True, null=True)),
                ('notes', core.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('created_at', core.fields.AutoCreatedAtField(auto_now_add=True)),
                ('updated_at', core.fields.AutoUpdatedAtField(auto_now=True)),
                ('source', core.fields.ChoiceIntegerField([(0, 'Walk-in'), (1, 'LinkedIn'), (2, 'Indeed'), (3, 'Glassdoor'), (4, 'JobStreet'), (5, 'Referral'), (6, 'Company Website'), (7, 'Facebook'), (8, 'Twitter / X'), (9, 'Other')])),
                ('status', core.fields.ChoiceIntegerField([(0, 'Wishlist'), (1, 'Applied'), (2, 'Interview'), (3, 'Offer'), (4, 'Rejected'), (5, 'Accepted')])),
                ('work_setup', core.fields.ChoiceIntegerField([(0, 'On-site'), (1, 'Remote'), (2, 'Hybrid')])),
                ('job_type', core.fields.ChoiceIntegerField([(0, 'Full-time'), (1, 'Part-time'), (2, 'Freelance'), (3, 'Contract'), (4, 'Internship'), (5, 'Temporary')])),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', core.fields.OptionalDateField(blank=True, null=True)),
                ('message', core.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('status', core.fields.ChoiceIntegerField([(0, 'No Response'), (1, 'Initial Follow-up'), (2, 'Reminder Email'), (3, 'Thank You Note'), (4, 'Checking for Updates'), (5, 'Interview Scheduled'), (6, 'Got a Response')])),
                ('reply', core.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('job', core.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.job')),
            ],
        ),
    ]
