# Generated by Django 5.2.1 on 2025-08-02 01:57

import core.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_remove_job_created_at_remove_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='created_at',
            field=core.fields.OptionalDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='updated_at',
            field=core.fields.OptionalDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=core.fields.OptionalDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=core.fields.OptionalDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
